### ISSUE TITLE
Incorrect tokens in agnostic encoding

### ISSUE THREAD

**Issue by davidrizo** [SEILSdataset/SEILSdataset#1]
There are some incorrect tokens in the agnostic encoding:

- dalocca_perose_T.agnostic: Mc## --> accidental.sharp-L3 note.minima-L3
- spontone_tamai_C.agnostic: Uiig --> note.fusa-L3
- spontone_tamai_Q.agnostic: ui6G	ui6F --> note.semifusa-S2 note.semifusa-L2

Thanks !!

**Comment by SEILSdataset** [comment]
Solved. 

Thank you for noticing it!!

**Comment by davidrizo** [comment]
The same tokens are found in the semantic encoding files

**Comment by SEILSdataset** [comment]
ok, corrected these as well.

Thanks!!
